### ISSUE TITLE
GUI: Missing emoji

### ISSUE THREAD

**Issue by nikonikoniko** [digitalevidencetoolkit/deptoolkit#23]
On linux the emoji's do not load in the app frontend.  My default font must not include all of them.

![2021-07-02-164434_3840x2160_scrot](https://user-images.githubusercontent.com/1519292/124291530-f3442f80-db54-11eb-94d1-d778a8abd191.png)

**Comment by basilesimon** [comment]
We have moved away from system emojis and to [`svelte-feather-icons`](https://www.npmjs.com/package/svelte-feather-icons):

![image](https://user-images.githubusercontent.com/5701152/128856197-8f764954-4ede-4406-972b-42e065a488f7.png)

Could you pull `main` and let me know if that addresses this issue on your OS?

**Comment by basilesimon** [comment]
On my Ubuntu machine, this is now rendering as expected. Closing for now, feel free to reopen if need be.
